//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServiceGolden
{
    using System;
    using System.Collections.Generic;
    
    public partial class canchas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public canchas()
        {
            this.partidos = new HashSet<partidos>();
            this.tipos_cancha = new HashSet<tipos_cancha>();
            this.turnos_fixture = new HashSet<turnos_fixture>();
        }
    
        public int id_cancha { get; set; }
        public string nombre { get; set; }
        public Nullable<float> capacidad { get; set; }
        public Nullable<int> id_domicilio { get; set; }
        public Nullable<int> id_club { get; set; }
    
        public virtual domicilios domicilios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partidos> partidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipos_cancha> tipos_cancha { get; set; }
        public virtual clubes clubes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<turnos_fixture> turnos_fixture { get; set; }
    }
}
