//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServiceGolden
{
    using System;
    using System.Collections.Generic;
    
    public partial class canchas
    {
        public int id_cancha { get; set; }
        public string nombre { get; set; }
        public Nullable<float> capacidad { get; set; }
        public Nullable<int> id_domicilio { get; set; }
        public Nullable<int> id_club { get; set; }
        public Nullable<int> id_tipo { get; set; }
    
        public virtual domicilios domicilios { get; set; }
        public virtual clubes clubes { get; set; }
        public virtual tipos_cancha tipos_cancha { get; set; }
    }
}
