//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServiceGolden
{
    using System;
    using System.Collections.Generic;
    
    public partial class fechas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fechas()
        {
            this.partidos = new HashSet<partidos>();
            this.fotos = new HashSet<fotos>();
            this.noticias = new HashSet<noticias>();
        }
    
        public int id_fecha { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_estado { get; set; }
        public Nullable<int> id_fixture { get; set; }
        public Nullable<int> id_fixture_zona { get; set; }
    
        public virtual estado_fecha estado_fecha { get; set; }
        public virtual fixture fixture { get; set; }
        public virtual fixture_zona fixture_zona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partidos> partidos { get; set; }
        public virtual fixture_zona fixture_zona1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fotos> fotos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<noticias> noticias { get; set; }
    }
}
