//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServiceGolden
{
    using System;
    using System.Collections.Generic;
    
    public partial class files
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string ImagePath { get; set; }
        public string ThumbPath { get; set; }
        public string ProjectId { get; set; }
        public string SectionId { get; set; }
        public int FileSize { get; set; }
    }
}
