//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServiceGolden
{
    using System;
    using System.Collections.Generic;
    
    public partial class partidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public partidos()
        {
            this.goles = new HashSet<goles>();
        }
    
        public int id_partido { get; set; }
        public Nullable<int> duracion { get; set; }
        public Nullable<int> id_fecha { get; set; }
        public Nullable<System.TimeSpan> hora_inicio { get; set; }
        public Nullable<System.TimeSpan> hora_fin { get; set; }
        public Nullable<int> local { get; set; }
        public Nullable<int> visitante { get; set; }
        public Nullable<int> id_arbitro { get; set; }
        public Nullable<int> id_estado { get; set; }
    
        public virtual arbitros arbitros { get; set; }
        public virtual equipos equipos { get; set; }
        public virtual equipos equipos1 { get; set; }
        public virtual estados_partidos estados_partidos { get; set; }
        public virtual fechas fechas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<goles> goles { get; set; }
    }
}
