//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServiceGolden
{
    using System;
    using System.Collections.Generic;
    
    public partial class pma__history
    {
        public decimal id { get; set; }
        public string username { get; set; }
        public string db { get; set; }
        public string table { get; set; }
        public System.DateTime timevalue { get; set; }
        public string sqlquery { get; set; }
    }
}
