//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServiceGolden
{
    using System;
    using System.Collections.Generic;
    
    public partial class pma__tracking
    {
        public string db_name { get; set; }
        public string table_name { get; set; }
        public long version { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_updated { get; set; }
        public string schema_snapshot { get; set; }
        public string schema_sql { get; set; }
        public string data_sql { get; set; }
        public string tracking { get; set; }
        public long tracking_active { get; set; }
    }
}
