//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServiceGolden
{
    using System;
    using System.Collections.Generic;
    
    public partial class pma__central_columns
    {
        public string db_name { get; set; }
        public string col_name { get; set; }
        public string col_type { get; set; }
        public string col_length { get; set; }
        public string col_collation { get; set; }
        public bool col_isNull { get; set; }
        public string col_extra { get; set; }
        public string col_default { get; set; }
    }
}
