//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServiceGolden
{
    using System;
    using System.Collections.Generic;
    
    public partial class pma__column_info
    {
        public long id { get; set; }
        public string db_name { get; set; }
        public string table_name { get; set; }
        public string column_name { get; set; }
        public string comment { get; set; }
        public string mimetype { get; set; }
        public string transformation { get; set; }
        public string transformation_options { get; set; }
        public string input_transformation { get; set; }
        public string input_transformation_options { get; set; }
    }
}
