//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServiceGolden
{
    using System;
    using System.Collections.Generic;
    
    public partial class pma__table_uiprefs
    {
        public string username { get; set; }
        public string db_name { get; set; }
        public string table_name { get; set; }
        public string prefs { get; set; }
        public System.DateTime last_update { get; set; }
    }
}
