//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServiceGolden
{
    using System;
    using System.Collections.Generic;
    
    public partial class pma__relation
    {
        public string master_db { get; set; }
        public string master_table { get; set; }
        public string master_field { get; set; }
        public string foreign_db { get; set; }
        public string foreign_table { get; set; }
        public string foreign_field { get; set; }
    }
}
