//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServiceGolden
{
    using System;
    using System.Collections.Generic;
    
    public partial class posiciones_zona
    {
        public int id_posicion { get; set; }
        public Nullable<int> id_equipo { get; set; }
        public Nullable<int> puntos { get; set; }
        public Nullable<int> goles_favor { get; set; }
        public Nullable<int> goles_contra { get; set; }
        public Nullable<int> dif_gol { get; set; }
        public Nullable<int> id_torneo { get; set; }
        public Nullable<int> id_zona { get; set; }
        public Nullable<int> partidos_jugados { get; set; }
        public Nullable<int> partidos_ganados { get; set; }
        public Nullable<int> partidos_empatados { get; set; }
        public Nullable<int> partidos_perdidos { get; set; }
    
        public virtual zonas zonas { get; set; }
        public virtual torneos torneos { get; set; }
    }
}
