//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServiceGolden
{
    using System;
    using System.Collections.Generic;
    
    public partial class resultados
    {
        public int id_resultado { get; set; }
        public Nullable<int> id_ganador { get; set; }
        public Nullable<int> id_perdedor { get; set; }
        public Nullable<sbyte> empate { get; set; }
    
        public virtual equipos equipos { get; set; }
        public virtual equipos equipos1 { get; set; }
    }
}
