//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServiceGolden
{
    using System;
    using System.Collections.Generic;
    
    public partial class turnos_fixture
    {
        public int id_turno_fixture { get; set; }
        public Nullable<int> id_cancha { get; set; }
        public Nullable<int> id_horario { get; set; }
    
        public virtual canchas canchas { get; set; }
        public virtual turnos turnos { get; set; }
    }
}
